<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<style type="text/css">
	@import url('<?php echo $this->base_url; ?>/css/fonts/futura.css');
	a.button {
	    background: none repeat scroll 0 0 #74A428;border: 1px solid #74A428;border-radius: 0px;box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.7);color: #FFFFFF;cursor: pointer;font-style: normal;padding: 4px 20px;width: auto;text-decoration: none;
	}
	a.button:hover {
		color: #ffffff;text-decoration: underline;
	}
	a {
		color: #73a329;text-decoration: none;
	}
	a:hover {
		text-decoration: underline;
	}
	</style>
</head>
<body style="font-family: 'FuturaBkBTBook', Verdana, Tahoma, Arial;font-size: 13px;line-height: 16px;color: #333;width: 670px;margin: auto;background-color: #ffffff;">
	<div style="width: 100%;height: 75px;background-color: #f6efd2;border: 1px solid #a9a491;margin: 10px 0px 20px 0px;">
		<img src="<?php echo $this->base_url; ?>/images/new/newsletter/petolio.png" width="56" height="92" style="float: left;margin: 0px 10px 0px 50px;" />
		<h1><?php printf("Hello %s", $this->name); ?></h1>
		<h2><?php echo $this->subject; ?></h2>
	</div>
	<div style="line-height: 22px;margin: 0px;padding: 0px 0px 20px 120px;">
		<?php echo $this->content; ?>
	</div>
	<div style="background-color: #74a528;width: 100%;height: 15px;padding: 0px;"></div>
</body>
</html>