<div class="left" style="width: 855px; padding-left: 50px;">
	<div class="icon left">
		<a href="<?php echo $this->url(array('controller'=>'galleries'), 'default', true); ?>" title="<?php echo $this->translate->_("Gallery"); ?>">
			<img src="/images/new/large/galery.png" />
		</a>
	</div>
	<div class="title left"><span><?php echo $this->translate->_("Become member of a<br/>large <i>community</i><br/>of pet owner and<br/>service provider."); ?></span></div>
	<div class="icon left">
		<img src="/images/new/large/medical.png" />
	</div>
	<div class="title left"><span><?php echo $this->translate->_("Use <i>Notes</i> to document all important issues depending to your pet"); ?></span></div>
	<div class="icon left">
		<a href="<?php echo $this->url(array('controller'=>'marketplace'), 'default', true); ?>" title="<?php echo $this->translate->_("Market Place"); ?>">
			<img src="/images/new/large/map.png" />
		</a>
	</div>
	<div class="title left"><span><?php echo $this->translate->_("Find and search<br/><i>service providers</i><br/>near to you."); ?></span></div>
	<div class="icon left">
		<a href="<?php echo $this->url(array('controller'=>'products'), 'default', true); ?>" title="<?php echo $this->translate->_("Market Place"); ?>">
			<img src="/images/new/large/market_place.png" />
		</a>
	</div>
	<div class="title left"><span><?php echo $this->translate->_("Always nice to<br/>serve through the<br/><i>marketplace</i>"); ?></span></div>
	<div class="icon left">
		<a href="<?php echo $this->url(array('controller'=>'events'), 'default', true); ?>" title="<?php echo $this->translate->_("Events"); ?>">
			<img src="/images/new/large/events.png" />
		</a>
	</div>
	<div class="title left"><span><?php echo $this->translate->_("Let yourself be invited<br/>to <i>events</i>"); ?></span></div>
	<div class="icon left">
		<a href="<?php echo $this->url(array('controller'=>'adoption'), 'default', true); ?>" title="<?php echo $this->translate->_("Pets"); ?>">
			<img src="/images/new/large/appointment.png" />
		</a>
	</div>
	<div class="title left"><span><?php echo $this->translate->_("Find and offer<br/><i>pets</i> in the<br/>market place"); ?></span></div>
	<div class="clear"></div>
</div>
<div class="right">
	<h5><?php echo $this->translate->_("Register now for <i>free</i>"); ?></h5>
	<?php echo $this->form; ?>
</div>