<?php if ($this->hasIdentity): ?>
	<?php include "menu.phtml"; ?>
	<div id="right" style="min-height: 550px;">
		<div class="rightbox">
			<div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down dash"><span></span></a></div></div>
			<h1><?php echo $this->translate->_("View Entry"); ?></h1>
			<br />
			<div class="disabler"></div>
			<div class="entries">
				<?php echo $this->partial('dashboard/feed.phtml', array(
		        	'translate' => $this->translate,
					'privacy' => $this->privacy,
		        	'results' => $this->results,
					'more' => $this->more,
					'identity' => $this->identity,
					'switch' => false
	    		)); ?>
			</div>
		</div>
	</div>
	<?php $imgsw_path = array(
		'image' => "{custom}",
		'audio' => "{custom}",
		'video' => "http://www.youtube.com/embed/{video}"
	); include "../application/modules/frontend/views/scripts/imgsw.phtml"; ?>
	<?php $dashboard_location = "view"; include "../application/modules/frontend/views/scripts/dashboard/init.phtml"; ?>
	<?php include "chat_online.phtml"; ?>
<?php else: include "notloggedin.phtml"; endif; ?>