<?php

// pet links
$accounts = array(
	array(
		'link' => $this->url(array('controller'=>'site', 'action'=>'index'), 'default', true),
		'name' => $this->translate->_("All Entries"),
		'class' => 'lm-dashboard_sm'
	),
	array(
		'link' => $this->url(array('controller'=>'site', 'action'=>'mine'), 'default', true),
		'name' => $this->translate->_("My Entries"),
		'class' => 'lm-dashboard_sm'
	),
	array(
		'link' => $this->url(array('controller'=>'site', 'action'=>'news'), 'default', true),
		'name' => $this->translate->_("Friends Entries"),
		'class' => 'lm-dashboard_sm'
	)
);

$links = null;
foreach($accounts as $link) {
	if ( isset($link['class']) && strlen($link['class']) > 0 ) {
		$links .= "<li style='width: auto;'><a style='padding-right: 5px;' href='{$link['link']}' class='{$link['class']}'><span>{$link['name']}</span></a></li>";
	} else {
		$links .= "<li style='width: auto;'><a style='padding-right: 5px;' href='{$link['link']}'>{$link['name']}</a></li>";
	}
}

if (!is_null($this->identity)) {
	$this->placeholder('sidebar')
	     ->append("<h3 data-hide='true'>".$this->translate->_("Options")."</h3>
	     	<ul class=\"leftsubmenu\" data-context=\"true\">{$links}</ul><div class=\"clear\"></div>");
}