<!-- decorator through view script, placed in 'views/scripts/file.phtml' -->
<div>
    <label for="<?php echo $this->element->getName(); ?>"><?php echo $this->element->getLabel(); ?></label>
    <?php if ($this->element->getDescription()): ?>
    	<div style="padding: 6px 0px 3px; float: left; margin: 0 0 0 5px;"><?php echo $this->element->getDescription(); ?></div>
    	<div style="display: none;"><?php echo $this->content; ?></div>
    <?php else: ?>
    	<div class="file"><?php echo $this->content; ?></div>
    	<div style="padding: 7px 0px 1px; float: left; margin: 0 0 0 5px; font-size: 12px; color:grey; "><?php echo $this->element->getAttrib('description'); ?></div>
    <?php endif; ?>
    <?php if ($this->element->hasErrors()) echo $this->formErrors($this->element->getMessages()); ?>
	<div class="cls"></div>
</div>