<table cellspacing="0" cellpadding="5" class="grid">
	<!--<col /><col width="200" /><col width="300" /><col width="100" />-->
	<tr>
		<th><?php echo $this->translate->_("Ticket No."); ?></th>
		<th><?php echo $this->translate->_("Date"); ?></th>
		<th><?php echo $this->translate->_("Name"); ?></th>
		<th><?php echo $this->translate->_("Email"); ?></th>
		<th><?php echo $this->translate->_("Description"); ?></th>
		<th><?php echo $this->translate->_("Amount"); ?></th>
		<th><?php echo $this->translate->_("Price"); ?></th>
		<th><?php echo $this->translate->_("Sum"); ?></th>
		<th><?php echo $this->translate->_("Status"); ?></th>
		<th></th>
	</tr>
	<?php foreach($this->data as $ticket): ?>
		<tr>
			<td><?php echo $ticket["ID"]; ?></td>
			<td><?php echo Petolio_Service_Util::formatDate($ticket["ticket_date"], null, true, true); ?></td>
			<td><?php echo $ticket["name"]; ?></td>
			<td><?php echo $ticket["email"]; ?></td>
			<td><?php echo $ticket["description"]; ?></td>
			<td><?php echo $ticket["amount"]; ?></td>
			<td><?php echo $ticket["price"]; ?></td>
			<td><?php echo number_format($ticket["amount"] * $ticket["price"], 2); ?></td>
			<td><?php echo $ticket["flgworkflow"]; ?></td>
			<td align="right" nowrap="nowrap">
				<?php foreach($this->links as $link): ?>
					<?php if ($link == "edit_status"):?>
						<a href='<?php echo $this->url(array('controller'=>'tickets', 'action'=>'manage-ticket-edit', 'ticket'=> $ticket["ID"]), 'default', true); ?>' class='icon_link edit'>
							<span><?php echo $this->translate->_('Edit'); ?></span>
						</a>
					<?php endif;?>
				<?php endforeach; ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
