<?php include "menu.phtml"; ?>
<div id="right">
	<div class="rightbox">
		<div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down"><span></span></a></div></div>
		<h1><?php echo $this->translate->_("Calendar"); ?></h1>
		<br />
		<div id="firebug_enabled"></div>
		<div id="calendar_canvas"></div>
	</div>
</div>
<?php include_once "init.phtml"; ?>
<script type="text/javascript">READY(Calendar.start);</script>