<?php printf($this->translate->_("Dear %s"), $this->name); ?>

<?php echo $this->translate->_("Thank you for registering in Petolio."); ?>
<?php echo $this->translate->_("To select a new password for your account please copy the following url and paste it into your browser:"); ?>

<?php echo $this->activationLink; ?>

<?php echo $this->translate->_("This link will be active for 7 days."); ?>


--
<?php echo $this->translate->_("Petolio team"); ?>