<?php printf($this->translate->_("Dear %s,"), $this->name); ?>


<?php echo $this->translate->_("We are glad that you have decided to use Petolio."); ?>
<?php echo $this->translate->_("To finish your registration please press"); ?> <a href="<?php echo $this->activationLink; ?>"><?php echo $this->translate->_("Activate"); ?></a>.


<?php echo $this->translate->_("Petolio team welcomes you as a member to one of the biggest pet lovers community online."); ?>
<?php printf($this->translate->_("Click on %s and use your e-mail and password to login."), "<a href='{$this->petolioLink}'>".$this->translate->_("Petolio")."</a>"); ?>


<?php echo $this->translate->_("We are looking forward to meeting you."); ?>


<?php echo $this->translate->_("Yours,"); ?>
<?php echo $this->translate->_("Petolio team"); ?>