<?php include "menu.phtml"; ?>
<div id="right">
	<div class="rightbox">
		<!-- <div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down"><span></span></a></div></div> -->
		<div>
			<div class="left"><img src="/images/new/large/help.png" alt="<?php echo $this->title; ?>" /></div>
			<ul class="title-menu">
				<li><h3><?php echo $this->title; ?></h3></li>
				<?php if($this->auth->hasIdentity()): ?>
				<li>
					<a href="<?php echo $this->url(array('controller'=>'help', 'action'=>'myquestions'), 'default', true); ?>" 
						title="<?php echo $this->translate->_("My Open Questions"); ?>">
						<?php echo $this->translate->_("My Open Questions"); ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url(array('controller'=>'help', 'action'=>'archives'), 'default', true); ?>" 
						title="<?php echo $this->translate->_("My Resolved Questions"); ?>">
						<?php echo $this->translate->_("My Resolved Questions"); ?>
					</a>
				</li>
				<?php endif; ?>
				<li>
					<?php
						echo $this->partial("help/search.phtml", array(
							"request" => $this->request,
							"translate" => $this->translate,
							"types" => $this->types,
							"status" => $this->status,
							"mine" => $this->mine,
							"auth" => $this->auth,
							"action" => $this->url(array('controller'=>'help'), 'default', true)."/index"
						));
					?>
				</li>
			</ul>
			<?php if($this->auth->hasIdentity()): ?>
			<div class="right">
				<a href="<?php echo $this->url(array('controller'=>'help', 'action'=>'add'), 'default', true); ?>" 
					title="<?php echo $this->translate->_("Ask Question"); ?>">
					<img src="/images/new/action/help_add.png" alt="<?php echo $this->translate->_("Ask Question"); ?>" />
				</a>
			</div>
			<?php endif; ?>
		</div>
		<div class="clear tenpx"></div>
		<?php if(isset($this->questions) && count($this->questions) > 0): ?>
			<?php echo $this->paginationControl($this->questions, 'Elastic', 'pagination-controls.phtml', array('pos' => 'top')); ?>
			<table cellspacing="0" cellpadding="5" class="help">
				<col width="70" /><col width="70" /><col /><col width="250" />
				<?php foreach($this->questions as $key => $question): ?>
					<?php echo $this->partial('question-template.phtml', array(
			        	'translate' => $this->translate,
						'key' => $key,
			        	'question' => $question
			    	)); ?>
			    <?php endforeach; ?>
			</table>
			<?php echo $this->paginationControl($this->questions, 'Elastic', 'pagination-controls.phtml', array('pos' => 'bot')); ?>
		<?php else: ?>
			<b class="red bigger"><?php echo $this->translate->_("No questions found."); ?></b>
		<?php endif; ?>
	</div>
</div>
<script type="text/javascript">
	var Microsite = function() {
		function open(url) {
			var identity = 'dialog-microsite';

			$("#"+ identity).remove();
			$('<div id="'+ identity +'" title="<?php echo $this->translate->_("View Microsite"); ?>" class="ui-state-highlight">'+
				'<div style="position: relative; margin: 8px 0px 2px 0px;">'+
					'<div id="frame_overlay" style="opacity: 0.9; background: white url(/images/ajax-loader.gif) center center no-repeat; position: absolute; top: 1px; left: 1px; width: 837px; height: 500px;"></div>'+
					'<iframe id="frame" name="microsite" src="'+ SITE_URL + url +'/index/iframe/true" width="837" height="500" scrolling="no" style="display: block; border: 1px solid #ddd;"></iframe>'+
				'</div>'+
			'</div>').dialog({
				resizable: false,
				modal: true,
				width: 862,
				minHeight: 50,
				buttons: [{
					text: '<?php echo $this->translate->_("Close"); ?>',
					click: function() {
						$(this).dialog("close");
					}
				}],
				close: function() {
					$("#"+ identity).remove();
				},
				open: function() {
					$('#frame').load(function() {
						$('#frame_overlay').fadeOut('fast');
						$("#frame").contents().find('a').click(function() {
							if( !$(this).hasClass('showloading') )
								return true;

							$('#frame_overlay').fadeIn('fast');
						});
					});
				}
			});
		};

		function __construct() {
			$('a.microsite').click(function() {
				open($(this).attr('rel'));
			});
		};

		return {
			init: __construct
		}
	}();

	var Privacy = function() {
		function hideFields() {
			$('[class*="private"], [class*="empty"]').each(function(s, i){
				var td = $(i).parent().parent();
				$(i).parent().remove();

				if(!td.has('span').length > 0)
					td.find('div').remove();
			});
		};

		function __construct() {
			hideFields();
		};

		return {
			init: __construct
		}
	}();

	READY(Microsite.init);
	READY(Privacy.init);
</script>