<div class="recommend_translate" style="display: none;"><?php echo json_encode(array(
	'blank' => $this->translate->_("Email addresses separated by a blank space..."),
	'sent' => $this->translate->_("Recommendation sent to %s people."),
)); ?>
</div>
<textarea style="font-size: 12px; margin: 10px 0px 0px 0px; padding: 4px; border: 1px solid #ccc; height: 45px; width: 270px;" name="recommend_body"><?php echo $this->translate->_("Email addresses separated by a blank space..."); ?></textarea><br />
<div style="float: left;"><div style="color: grey; margin-top: 8px;"><span class="recommend_count">1500</span> <?php echo $this->translate->_("characters remaining"); ?></div></div>
<div style="float: right;"><input type="submit" class="submit" style="margin-top: 5px;" name="recommend_submit" value="<?php echo $this->translate->_("Send"); ?>" /></div>
<div style="clear: both;"></div>