<div id="right">
	<div class="rightbox">
		<div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down"><span></span></a></div></div>
		<h1><?php echo $this->translate->_("Send a private message"); ?></h1>
		<br />
		<?php echo $this->form; ?>
	</div>
</div>
<script type="text/javascript">
var Compose = function() {
	var user = {id: '<?php echo $this->user->getId(); ?>', name: '<?php echo $this->user->getName(); ?>'};

	function addTo() {
		$("#subject").closest('div').before(
			'<div>'+
			'<label for="captcha_picture"><?php echo $this->translate->_("To"); ?>:</label>'+
			'<input type="hidden" name="to_user_id" id="to_user_id" value="' + user.id + '" />' +
			'<input type="text" id="multi_users" value="'+ user.name +'" disabled="disabled" style="background: none; border: none; padding: 6px 0px 4px;" />'+
			'<div class="cls"></div>'+
		'</div>');
	};

	function __construct() {
		addTo();
	};

	return {
		init: __construct
	};
}();

READY(Compose.init);
</script>