<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php echo $this->headTitle(); ?>
		<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	</head>
	<body>
		<h2><?php echo $this->message; ?></h2>
		<center>
			<input type="button" value="<?php echo $this->translate->_("Close"); ?>" onclick="window.close()" />
		</center>
	</body>
</html>