<?php $userTypes = array("1" => $this->translate->_("Pet Owner"), "2" => $this->translate->_("Service Provider")); ?>
<div id="right">
	<div class="rightbox">
		<div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down"><span></span></a></div></div>
		<h1><?php echo $this->title; ?></h1>
		<br />
		<?php if(isset($this->paginator) && count($this->paginator) > 0): ?>
			<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination-controls.phtml', array('pos' => 'top')); ?>
			<?php include "grid-online.phtml"; ?>
			<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination-controls.phtml', array('pos' => 'bot')); ?>
		<?php else: ?>
			<b class="red bigger"><?php echo $this->translate->_("No online members found."); ?></b>
		<?php endif; ?>
	</div>
</div>
<script type="text/javascript">
	var Microsite = function() {
		function open(url) {
			var identity = 'dialog-microsite';

			$("#"+ identity).remove();
			$('<div id="'+ identity +'" title="<?php echo $this->translate->_("View Microsite"); ?>" class="ui-state-highlight">'+
				'<div style="position: relative; margin: 8px 0px 2px 0px;">'+
					'<div id="frame_overlay" style="opacity: 0.9; background: white url(/images/ajax-loader.gif) center center no-repeat; position: absolute; top: 1px; left: 1px; width: 837px; height: 500px;"></div>'+
					'<iframe id="frame" name="microsite" src="'+ SITE_URL + url +'/index/iframe/true" width="837" height="500" scrolling="no" style="display: block; border: 1px solid #ddd;"></iframe>'+
				'</div>'+
			'</div>').dialog({
				resizable: false,
				modal: true,
				width: 862,
				minHeight: 50,
				buttons: [{
					text: '<?php echo $this->translate->_("Close"); ?>',
					click: function() {
						$(this).dialog("close");
					}
				}],
				close: function() {
					$("#"+ identity).remove();
				},
				open: function() {
					$('#frame').load(function() {
						$('#frame_overlay').fadeOut('fast');
						$("#frame").contents().find('a').click(function() {
							if( !$(this).hasClass('showloading') )
								return true;

							$('#frame_overlay').fadeIn('fast');
						});
					});
				}
			});
		};

		function __construct() {
			$('a.microsite').click(function() {
				open($(this).attr('rel'));
			});
		};

		return {
			init: __construct
		}
	}();

	var Privacy = function() {
		function hideFields() {
			$('[class*="private"], [class*="empty"]').each(function(s, i){
				var td = $(i).parent().parent();
				$(i).parent().remove();

				if(!td.has('span').length > 0)
					td.find('div').remove();
			});
		};

		function __construct() {
			hideFields();
		};

		return {
			init: __construct
		}
	}();

	READY(Microsite.init);
	READY(Privacy.init);
</script>