<!-- 
<div id="right">
	<div class="rightbox">
		<div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down"><span></span></a></div></div>
		<h1><?php echo $this->translate->_("My Profile"); ?></h1>
		<?php include "profile-info.phtml"; ?>
		<div>
			<label>&nbsp;</label>
			<input type="submit" value="<?php echo $this->translate->_("Edit Profile Information >"); ?>" id="submit" name="submit" onclick="Petolio.go('<?php echo $this->url(array('controller'=>'accounts', 'action'=>'edit'), 'default', true); ?>');">
			<div class="cls"></div>
		</div>
	</div>
	<br /><br /><br /><br />
</div>
-->
<?php include "menu.phtml"; $this->render('accounts/profile-picture.phtml'); ?>
<div id="right">

	<?php
		if ($this->user->getType() == 1):
			include 'view-pet-owner.phtml';
		else:
			include 'view-service-provider.phtml';
			/* include 'view-profile.phtml';
			if($this->microsite) include 'view-microsite.phtml';
			if($this->yourServices->getTotalItemCount() > 0) include 'view-services.phtml';
			if($this->yourPets->getTotalItemCount() > 0) include 'view-pets.phtml';
			if($this->auth->hasIdentity() && isset($this->your_events) && count($this->your_events) > 0) include 'view-events.phtml';
			if($this->auth->hasIdentity()) include 'view-dashboard.phtml'; */
		endif;
	?>

</div>