<style>
	div.faq > div > div > a,
	div.faq > div > div > ul > li > a {
		font-size: 12px;
	}

	div.faq > div > div > ul {
		padding-left: 30px;
	}
</style>
<div class="faq">
	<div>
		<h3>What are cookies?</h3>
		<div>A cookie (web cookie, or browser cookie) is a small file which is stored on your computer when you visit a website. These files are used by the website for a number of things but mainly to remember where you have been on the website and what you are searching for.</div>
		<div>In some cases cookies also assist in any interaction between you and the website, for example when using social media such as <a href="http://facebook.com">facebook</a> and <a href="http://youtube.com">youtube</a>.</div>
		<div>For a more details <a href="http://en.wikipedia.org/wiki/HTTP_cookie">read more about cookies on Wikipedia</a>.</div>
	</div>
	<div>
		<h3>How does Petolio use cookies?</h3>
		<div>We actively use cookies to record how our visitors use and browse around our website. This helps us determine popular and unpopular pages and lets us know where we need to improve and what services we may need need to promote or update.</div>
		<div>In order to achieve this we use the popular <a href="http://www.google.com/analytics/">Google Analytics</a> system which shows us what our most popular sections are, what our users type into Google in order to find us and how effective our news and media campaigns are.</div>
		<div>We use other types of cookies sparingly and <strong>only</strong> when needed. For example we keep track of your login information and your language and timezone settings as well as some other smaller settings for each page individually.</div>
	</div>
	<div>
		<h3>What do these cookies look like?</h3>
		<div>If you check your web browser settings for the cookies that our site has stored on your computer you should see:</div>
		<div>
			<table class="grid" style="font-size: 12px;">
			<tr>
				<th>Cookie Name</th>
				<th>Purpose</th>
				<th>Cookie Identifier</th>
			</tr>
			<tr>
				<td>Google Analytics</td>
				<td>Tracks how you use our website, which areas you visit and how you found our website. Also tells us about how you accessed our site (if you used a mobile or PC for example) and how long you spent reading information.</td>
				<td>__utma<br>__utmb<br>__utmc<br>__utmz</td>
			</tr>
			<tr>
				<td>Petolio Language &amp; User Timezone</td>
			    <td>Used to determine what language the website is on and the user's timezone.</td>
			    <td>petolio_language<br>user_timezone</td>
			</tr>
			<tr>
				<td>Petolio Chat Services</td>
			    <td>In order to use the chat services we keep these cookies, the ifm_online cookie is the settings for the chat sidebar and all of the options it has.</td>
			    <td>APE_Cookie<br>ifm_online</td>
			</tr>
			<tr>
				<td>Petolio Forum</td>
			    <td>We use a separate system for our forum and that will also save cookies related to login information and last viewed topics in order to mark them as read.</td>
			    <td>pun_cookie_[random_string]</td>
			</tr>
			</table>
		</div>
	</div>
	<div>
		<h3>Other ways your information may be tracked via our website</h3>
		<div>As we integrate with popular websites like <a class="" href="http://facebook.com">Facebook</a> and <a href="http://youtube.com">YouTube</a> it is important to note that these sites may also use cookies of their own which may sometimes be stored through our website.</div>
		<div>For more information on these cookies you should view the respective privacy polices for each of these sites:</div>
		<div>
			<ul>
				<li><a href="http://www.facebook.com/about/privacy/">Facebook privacy policy</a></li>
			    <li><a href="http://support.google.com/youtube/bin/answer.py?hl=en&amp;answer=95531">YouTube (Google) privacy policy</a></li>
			</ul>
		</div>
	</div>
	<div>
		<h3>Questions and queries</h3>
		<div>If you have any further queries about how our website uses cookies then feel free to <a href="/contact/">contact us</a>.</div>
	</div>
</div>