<style>
	div.faq > div > div > a,
	div.faq > div > div > ul > li > a {
		font-size: 12px;
	}

	div.faq > div > div > ul {
		padding-left: 30px;
	}
</style>
<div class="faq">
	<div>
		<h3>Was sind Cookies?</h3>
		<div>Ein Cookie (web cookie oder browser cookie), ist eine Textinformation, die die besuchte Website (hier „Server“) über den Browser im Rechner des Betrachters („Client“) platziert.</div>
		<div>Der Cookie wird entweder vom Webserver an den Browser gesendet oder von einem Skript (etwa JavaScript) in der Website erzeugt. Der Client sendet die Cookie-Information bei späteren, neuen Besuchen dieser Seite mit jeder Anforderung wieder an den Server.</div>
		<div>Weiter Informationen <a href="http://en.wikipedia.org/wiki/HTTP_cookie">findest Du auf Wikipedia</a>.</div>
	</div>
	<div>
		<h3>Wie benutzt Petolio Cookies?</h3>
		<div>Wir benutzen die Cookies um das Surfverhalten unserer Anwender auf dem Petolio Server mitzuverfolgen. Dies hilft uns zu lernen, welche Themen für unsere Besucher wichtig sind, bzw. welche eher zweitrangig. Mit diesen Informationen können wir die Funktionen und Dienstleistungen für unsere Besucher und Mitglieder ständig verbessern.</div>
		<div>Um dies möglichst effizient zu erreichen, verwenden wir <a href="http://www.google.com/analytics/">Google Analytics</a>.</div>
		<div>Grundsätzlich verwenden wir Cookies nur in Ausnahmefällen. Wir sichern Zeitzonen, Spracheinstellungen und besondere Einstellungen für Services, wie dem Forum.</div>
	</div>
	<div>
		<h3>Wie sehen diese Cookies aus?</h3>
		<div>
			<table class="grid" style="font-size: 12px;">
			<tr>
				<th>Cookie Namen</th>
				<th>Zweck</th>
				<th>Cookie-Identifier</th>
			</tr>
			<tr>
				<td>Google Analytics</td>
				<td>Verfolgt die Art, wie der Besucher Petolio benutzt, welche Seiten er aufruft und wie der Besucher Petolio gefunden hat. Google wertet auch aus, welche Hardware (PC oder Mobil) oder Software (Browser) und zeigt die Dauer des Besuches an.</td>
				<td>__utma<br>__utmb<br>__utmc<br>__utmz</td>
			</tr>
			<tr>
				<td>Petolio Spracheauswahl und Zeitzone</td>
			    <td>Mit diesem Cookie ermittelt Petolio welche bevorzugte Sprachauswahl für den Besucher wichtig ist. Außerdem stellt Petolio die Zeitzone fest, in der sich der Besucher aufhält.</td>
			    <td>petolio_language<br>user_timezone</td>
			</tr>
			<tr>
				<td>Petolio Chat Services</td>
			    <td>Diese Cookies werden für den Chat Service benötigt. Das ifm_online cookie wird für die Sidebar des Chat und ihre Optionen benötigt.</td>
			    <td>APE_Cookie<br>ifm_online</td>
			</tr>
			<tr>
				<td>Petolio Forum</td>
			    <td>Das Forum wird durch eine Drittsoftware bereitgestellt, welches durch die Einwahl ebenfalls Cookies benötigt. Dabei merken sich die Cookies vor allem, welche Seiten bereits angesehen wurden, bzw. an welchen Stellen es neue Einträge gibt, die der Besucher noch nicht gesehen hat.</td>
			    <td>pun_cookie_[random_string]</td>
			</tr>
			</table>
		</div>
	</div>
	<div>
		<h3>Weitere Cookies, die möglicherweise verwendet werden können</h3>
		<div>In manchen Bereichen stellt Petolio Verbindungen zu <a class="" href="http://facebook.com">Facebook</a> und <a href="http://youtube.com">YouTube</a> dar. Diese Webseiten wiederum verwenden unabhängig von Petolio selber Cookies, die durch die Verwendung derer Dienste auf Petolio durch die jeweiligen Unternehmen gespeichert werden können.</div>
		<div>Weitere Informationen wie die jeweiligen Unternehmen Cookies einsetzen, finden Sie auf den folgenden Seiten:</div>
		<div>
			<ul>
				<li><a href="http://www.facebook.com/about/privacy/">Facebook privacy policy</a></li>
			    <li><a href="http://support.google.com/youtube/bin/answer.py?hl=en&amp;answer=95531">YouTube (Google) privacy policy</a></li>
			</ul>
		</div>
	</div>
	<div>
		<h3>Für weitere Fragen oder Unklarheiten</h3>
		<div>Für weitere Fragen oder Unklarheiten, wie Petolio Cookies verwendet, freuen wir uns, wenn Sie und <a href="/contact/">kontaktieren</a>.</div>
	</div>
</div>