<div class="rightbox">
	<h2><?php echo $this->translate->_("Credits and Responsibilities"); ?></h2>
	<center>
		<br/>
		Web Entertainment AG<br/>
		Seefeldstraße 60<br/>
		8008 Zürich<br/>
		Switzerland<br/>
		<?php echo $this->translate->_("Telefon"); ?>: +49 175 4290 160<br/>
		<a href="mailto:info@wenag.eu">info@wenag.eu</a><br/>
		<?php echo $this->translate->_("Registration No."); ?>: Zürich, CH-020.3.028.275-7<br/>
		<?php echo $this->translate->_("Sales tax identification number"); ?>: CHE112137244<br/>
		<br/>
		<?php echo $this->translate->_("Editorial and contact person:"); ?><br/>
		Frank Kiau<br/>
	</center>
</div>