<?php include "menu.phtml"; ?>
<div id="right">
	<div class="rightbox">
		<div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down"><span></span></a></div></div>
		<h1><?php echo $this->translate->_("Data Protection"); ?></h1>
		<?php if(strcasecmp($this->translate->getLocale(), 'en') == 0) include "data-en.phtml"; ?>
		<?php if(strcasecmp($this->translate->getLocale(), 'de') == 0) include "data-de.phtml"; ?>
	</div>
</div>