<div class="faq">
	<div>
		<h3>Welche Kosten fallen bei Petolio an?</h3>
		<div>Petolio ist sowohl f&#252;r Haustierbesitzer, wie auch f&#252;r Dienstleister kostenfrei. Innerhalb von Petolio gibt es, oder wird es in Zukunft Dienste  geben, die m&#246;glicherweise mit Kosten verbunden sind. Diese sind aber ausgezeichnet und m&#252;ssen best&#228;tigt werden.</div>
	</div>
	<div>
		<h3>Was ist der Unterschied zwischen einem Haustierbesitzer und einem Dienstleister?</h3>
		<div>Der Haustierbesitzer nutzt die M&#246;glichkeiten von Petolio. Er kn&#252;pft Freundschaften zu anderen Tierbesitzern, registriert seine Tiere, nimmt an Veranstaltungen teil und nutzt die von Dienstleistern pr&#228;sentierten Leistungen. Er verkn&#252;pft sein Tier mit einem Dienstleister und kann dann Funktionen, wie das F&#252;hren eines medizinischen Tagebuches, Terminvereinbarungen oder Teilnahme an Events und Veranstaltungen nutzen.</div>
		<div>Der Dienstleister ist wahrscheinlich auch ein Tierbesitzer und nutzt somit die gleichen Funktionen. Dar&#252;ber hinaus kann er sein Unternehmen pr&#228;sentieren und eine Reihe von Dienstleistungen anbieten.</div>
		<div>So finden einfach und schnell alle Personen, die Leistungen suchen zu denen, die Leistungen anbieten.</div>
	</div>
	<div>
		<h3>F&#252;r welche Tiere ist das Portal geeignet?</h3>
		<div>Im Grundsatz f&#252;r alle. Heute sind prim&#228;r die Haustiere ber&#252;cksichtigt. Dazu geh&#246;ren neben Katze, Hund, Vogel, Pferd etc. nat&#252;rlich auch Reptilien, Fische oder Schildkr&#246;ten. Und wer keine passende Kategorie findet w&#228;hlt einfach Sonstige und definiert seine Besonderheiten.</div>
	</div>
	<div>
		<h3>Wie kann ich meine Daten sch&#252;tzen?</h3>
		<div>Deine pers&#246;nlichen Daten kannst Du in Deinem Profil verwalten und einstellen. F&#252;r jedes einzelne Feld kannst Du bestimmen, wer diese Daten sehen darf und wer nicht. Du musst nicht alle Felder ausf&#252;llen, aber in bestimmten F&#228;llen macht es Sinn dies zu tun.</div>
		<div>Alle weiteren Daten, wie z.B. das medizinische Tagebuch oder Dateien, wie R&#246;ntgenbilder kannst Du ganz individuell sch&#252;tzen und somit den Zugriff selber beeinflussen.</div>
	</div>
	<div>
		<h3>Wo kann ich meine pers&#246;nlichen Daten eingeben?</h3>
		<div>In der oberen, rechten Bildschirmecke findest Du den Men&#252;punkt &#8222;Profil&#8220;. Wenn Du den anw&#228;hlst und dann &#8222;Profil bearbeiten&#8220; anw&#228;hlst, kannst Du Deine pers&#246;nlichen Daten eingeben oder ver&#228;ndern. Vergesse nach der Eingabe nicht zu speichern. Unter Profiloptionen kannst Du Dein Profilbild &#228;ndern.</div>
	</div>
	<div>
		<h3>Warum soll ich meine Tiere registrieren?</h3>
		<div>Es gibt Leistungen und Funktionen, die speziell f&#252;r die Haustiere erstellt wurden. Du kannst beispielsweise ein medizinisches Tagebuch f&#252;hren. Wenn Du mit Deinem Tier eine Partnerschaft zu einem Dienstleister, wie ein Tierarzt erstellt hast, dann kann dieser auch Eintr&#228;ge in Deine Krankenakte t&#228;tigen. Du kannst auch digitale R&#246;ntgenbilder einstellen und Dienstleistern den Zugriff darauf gew&#228;hren um noch eine Drittmeinung einzuholen.</div>
		<div>Auch der Terminkalender f&#252;r Erinnerungen, wie Impftermine hat einen Bezug zu Deinem Haustier. Zu guter Letzt freuen sich auch Deine Freunde und Bekannte Neuigkeiten, Bilder oder Videos von Deinen Tieren mitzuerleben.</div>
	</div>
	<div>
		<h3>Wie funktioniert der Stammbaum?</h3>
		<div>F&#252;r jedes Tier wird automatisch auch die Funktion des Stammbaumes erstellt. Man kann selber Vorfahren eingeben, oder eine Verbindung zu einem eingestellten Tier herstellen.</div>
	</div>
	<div>
		<h3>Was ist der Tiermarkt?</h3>
		<div>Wenn Du ein Haustier abgeben m&#246;chtest, dann kannst Du es in den Tiermarkt einstellen. M&#246;gliche Interessenten k&#246;nnen dann mit Dir Kontakt aufnehmen. Du kannst jederzeit Dein Tier aus dem Tiermarkt wieder entfernen. Wenn die &#220;bergabe des Tieres an einen neuen Besitzer vollzogen ist, k&#246;nnt ihr das Tierprofil mit allen Eintragungen und Daten an den neuen Besitzer &#252;bertragen. Er erh&#228;lt so auch das medizinische Tagebuch.</div>
	</div>
	<div>
		<h3>Wann archiviere ich mein Tier?</h3>
		<div>Wenn Du Dein Tier archivierst, dann ist es nicht mehr einsehbar, es bleibt aber weiter bestehen. Du kannst es jederzeit reaktivieren.</div>
	</div>
	<div>
		<h3>Wie kann ich Freunde finden?</h3>
		<div>Im Bereich &#8222;Freunde finden&#8220; kannst Du direkt suchen. Entweder kennst Du den Namen oder hast weitere Anhaltspunkte, wie Postleitzahl, Bundesland oder weiteres. Im Men&#252;bereich Mitglieder kannst Du auch surfen und schaun, ob Du vielleicht zuf&#228;llig jemanden bekanntest triffst. Du kannst dann einer Person eine Freundschaftsanfrage schicken, die die Person dann beantwortet. Ihr k&#246;nnt Euch auch Nachrichten zusenden, oder auf dem k&#252;nftigen schwarzen Brett miteinander diskutieren.</div>
	</div>
	<div>
		<h3>Wozu brauche ich denn noch einen Kalender?</h3>
		<div>Das ist eine berechtigte Frage. Dieser Kalender hat eine Menge Funktionen, die eine Verbindung zu einem Dienstleister herstellt. Wenn Dich ein Verein, in dem Du Mitglied bist, zu einer Feier einl&#228;dt, und Du die Einladung akzeptierst, dann wird der Termin automatisch in den Kalender eingetragen. Du kannst aber auch Terminanfragen an Dienstleister schicken, zu denen Du bereits eine Partnerschaft unterh&#228;lst, z.B. vereinbare einen Termin mit Deinem Hufschmied. Das macht die Zusammenarbeit wesentlich einfacher und macht auch richtig Spa&#223;.</div>
	</div>
	<div>
		<h3>Wie finde ich einen Dienstleister?</h3>
		<div>Du kannst im Bereich der Mitglieder die Liste der Tierbesitzer und Dienstleister einsehen. Im Marktplatz findest Du eine Darstellung der unterschiedlichen Services, die von Dienstleistern angeboten werden. Wenn Du dringend einen Dienstleister in Deiner N&#228;he suchst, kannst Du in der Landkarte die Services in Deiner unmittelbaren Umgebung finden. Mit Hilfe der Filter und Suchfunktion kannst Du detailliert suchen.</div>
	</div>
	<div>
		<h3>Was ist der Unterschied zwischen Mitgliedschaft und Partnerschaft?</h3>
		<div>Es gibt Dienste, die sich auf Mitgliedschaften st&#252;tzen. Dazu z&#228;hlen Vereine, Verb&#228;nde oder &#228;hnliches. Hier wirst Du als Person Mitglied, das hat mit Deinem Haustier nicht direkt etwas zu tun. Es gibt aber auch Dienste, die sich direkt an Deine Haustiere richten. Dazu geh&#246;rt der Hundefriseur, der Pferdepensionsstall oder der Tierarzt. Diese Leistungen beziehen sich auf Dein Tier. Deshalb kannst Du auch mehrere Partnerschaften zu einem Dienstleister haben, z.B. wenn Du eine Katze und einen Hund mit einem Tierarzt verbinden m&#246;chtest.</div>
	</div>
	<div>
		<h3>Wer kann Dienstleistungen anbieten?</h3>
		<div>Bei der Registrierung wird zwischen dem Haustierbesitzer und dem Dienstleister unterschieden. Der Dienstleister wird wahrscheinlich auch ein Haustierbesitzer sein, daher verf&#252;gt er &#252;ber die gleichen Funktionen, er kann aber zus&#228;tzlich noch eine Firmendarstellung hinterlegen und verschiedene Services aufbauen. Au&#223;erdem kann er Veranstaltungen und Events planen und seine Mitglieder und Partner dazu einladen. Es gibt eine Vielzahl an M&#246;glichkeiten.</div>
	</div>
	<div>
		<h3>Wozu ist das Forum gedacht?</h3>
		<div>Der Bedarf an Kommunikation ist riesig. Der Vorteil von Petolio ist, dass eine gro&#223;e Community von Haustierbesitzern und Dienstleistern sich gegenseitig unterst&#252;tzen k&#246;nnen.</div>
		<div>Bitte bedenke, dass auch Mitglieder anderer Nationalit&#228;ten Petolio benutzen. Kommuniziere in Englisch, wenn Du Dich auch mit Menschen anderer Nationalit&#228;ten austauschen m&#246;chtest.</div>
	</div>
</div>