<div class="faq">
	<div>
		<h3>How much does Petolio cost?</h3>
		<div>Using Petolio is free, both for pet owners and for service providers. There might be services which will require payment in the future, but it's up to you to use them or not.</div>
	</div>
	<div>
		<h3>What is the difference between a pet owner and a service provider?</h3>
		<div>Basically the pet owner is using Petolio to create new friendships or register their pets. The owner takes part in events or appointments, and they create links with services to use the additional features like the medical records, or creating appointments with service providers.</div>
		<div>A service provider might also be a pet owner and so, he can use the same features like the regular pet owner. In addition the provider can create and present services and support them to find existing or new clients. He can provide a website to his company by creating a microsite. Only the service provider can create special events and invite friends and partners.</div>
	</div>
	<div>
		<h3>Is Petolio restricted to special species?</h3>
		<div>No. Every species is welcome. The customized species today are pets. That includes cats, dogs, birds, horses as well as reptiles, fish or turtles and a whole lot more. If there is a category missing, you have the opportunity to create your own.</div>
	</div>
	<div>
		<h3>How can I save my data?</h3>
		<div>Your personal data is organized in your profile. For every field you have the opportunity to define access rights. It is not necessary to fill out every field, although it will make it easier for your friends and partners to contact you.</div>
	</div>
	<div>
		<h3>Where can I define my personal data?</h3>
		<div>Located in the menu you find the profile links. Here you can edit all your personal data and upload a profile picture.</div>
	</div>
	<div>
		<h3>Why should I register my pets?</h3>
		<div>Petolio offers features that work only when you link them to your pet. Creating a medical record belongs to a pet; If you want to create a partnership with a service, it is necessary to link it to your pet. Think about a partnership to an animal doctor.</div>
		<div>Or you may want to create appointments with a service provider e.g. a blacksmith. This belongs to your pet as well, though the pet owner pays the ckeck.</div>
		<div>Further more, you will have the means to present your pet by uploading pictures or videos and creating a presentation gallery. This is fun to all your friends.</div>
	</div>
	<div>
		<h3>How does the pedigree work?</h3>
		<div>Every pet you register will automatically have its own pedegree. You can enter your individual information or create links to other registered pets.</div>
	</div>
	<div>
		<h3>What is the adoption list?</h3>
		<div>If you would like to adopt or submit your pet for adoption, you can create a link in the adoption page. All members have access to the adoption page and they can show interest towards them. If you decide to give your pet away, you would be able to transfer the pet's data to the new owner.</div>
	</div>
	<div>
		<h3>When do I archive my pet?</h3>
		<div>When you archive your pet, other members will not be able to see it anymore, but it stays available. You can restore your pet back at any time.</div>
	</div>
	<div>
		<h3>How can I find friends?</h3>
		<div>Press the "find friends" button and type in the name of your friend and then select him from the list. If you do not know the name, you can use the membership list and use the existing database. After you find your friends you can create a friendship request. After your friend has accepted your request, he will be listed in your friendship list.</div>
	</div>
	<div>
		<h3>What is the calendar for?</h3>
		<div>This calendar offers you a lot of useful features. You can create your personal tasks, notes and appointments that are only for you. You can also make appointments with partners that are automatically listed in your calendar. If you decide to delete the appointments, your partner or friend will be automatically informed.</div>
		<div>Your partners may invite you to their event. If you accept the invitation, the event will be listed in your calendar. The reminder feature takes care that you will never miss a date.</div>
	</div>
	<div>
		<h3>How do I find a service provider?</h3>
		<div>The best way to find a service provider is by going to the market place. You will find the different services offered by the services provider. On one hand you can use the search feature or you can go straight to the map and find a service near to you.</div>
	</div>
	<div>
		<h3>What is the difference between membership and partnership?</h3>
		<div>That depends on the service. Some services only adress the members and not their pets. Think about an association where a user can be a member. Most of the services however, are adressing the pets so a partnership is created betweem a pet and service provider. The pet owner can own several pets so each one of them can have one or more partnerships to different service providers.</div>
	</div>
	<div>
		<h3>Who can create services?</h3>
		<div>Only service providers can create services.</div>
	</div>
	<div>
		<h3>What is the idea of the forum?</h3>
		<div>Pet owners might want to discuss and communicate with each other. So if you need support, you can create an entry in the forum and our existing members will answer and help you out.</div>
		<div>Petolio is an international portal; that means that a lot of different cultures use this service. If you want to discuss your issues please use the English language.</div>
	</div>
</div>