<?php include "menu.phtml"; ?>
<div id="right">
	<div class="rightbox">
		<div class="context"><div class="in"><a href="javascript:void(0);" id="context_menu" class="icon_link the_down"><span></span></a></div></div>
		<h1><?php echo $this->translate->_('Archived Services'); ?></h1>
		<br />
		<?php if(isset($this->archived) && count($this->archived) > 0): ?>
			<?php echo $this->paginationControl($this->archived, 'Elastic', 'pagination-controls.phtml', array('pos' => 'top')); ?>
			<table cellspacing="0" cellpadding="5" class="grid">
				<col width="35%" /><col width="25%" /><col width="20%" /><col width="20%" />
				<tr>
					<th><a href="<?php echo $this->url(array('order' => 'name', 'dir' => $this->rdir)); ?>"><?php echo $this->translate->_("Name"); ?><?php if($this->order == 'name'): ?>&nbsp;<img src="/images/order/<?php echo $this->dir; ?>.png" /><?php endif; ?></a></th>
					<th><a href="<?php echo $this->url(array('order' => 'type', 'dir' => $this->rdir)); ?>"><?php echo $this->translate->_("Type"); ?><?php if($this->order == 'type'): ?>&nbsp;<img src="/images/order/<?php echo $this->dir; ?>.png" /><?php endif; ?></a></th>
					<th><a href="<?php echo $this->url(array('order' => 'date', 'dir' => $this->rdir)); ?>"><?php echo $this->translate->_("Date"); ?><?php if($this->order == 'date'): ?>&nbsp;<img src="/images/order/<?php echo $this->dir; ?>.png" /><?php endif; ?></a></th>
					<th></th>
				</tr>
				<?php foreach($this->archived as $service): ?>
					<tr>
						<td><?php echo $service["name"]; ?></td>
						<td><a href="<?php echo $this->url(array('controller'=>'services', 'action'=>'index', 'type' => $service["attribute_set_id"]), 'default', true); ?>"><?php echo $service["type"]; ?></a></td>
						<td><?php echo Petolio_Service_Util::formatDate($service["date_created"], null, true, true); ?></td>
						<td align="right" nowrap="nowrap">
							<a href='<?php echo $this->url(array('controller'=>'services', 'action'=>'restore', 'service'=> $service["id"]), 'default', true); ?>' class='icon_link restore reqconf' title="<?php echo sprintf($this->translate->_('Are you sure you want to restore the %s service?'), $service['name']); ?>">
								<span><?php echo $this->translate->_('Restore'); ?></span>
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</table>
			<?php echo $this->paginationControl($this->archived, 'Elastic', 'pagination-controls.phtml', array('pos' => 'bot')); ?>
		<?php else: ?>
			<b class="red bigger"><?php echo $this->translate->_('No services archived.'); ?></b>
		<?php endif; ?>
	</div>
</div>