<div class="right" style="float: none;">
	<div class="rightbox">
		<h1><?php echo $this->translate->_("Ups, the site you have asked for does not exist."); ?></h1>
		<br />
		<span class="red bigger" style="line-height: 18px;"><?php echo $this->message ?>.<br /><a style="font-size:12px;" href="/site"><?php echo $this->translate->_("Click here to go to Petolio's Homepage"); ?>.</a></span>
		<?php if (isset($this->exception)): ?>
			<br /><br />
			<h3>Exception information:</h3>
			<p class="petolio">
				<b>Message:</b> <?php echo $this->exception->getMessage() ?>
			</p>
			<h3>Stack trace:</h3>
			<pre><?php echo $this->exception->getTraceAsString() ?>
			</pre>
			<h3>Request Parameters:</h3>
			<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
		<?php endif ?>
	</div>
</div>