<?php

// jsonp
$href = null;
if($this->jsonp)
	$href = "data-petolio='true'";

if ($this->pageCount > 1): ?>
	<div class="clear <?php if($this->pos == 'bot') echo 'tenpx'; ?>"></div>
		<?php if (isset($this->previous)): ?>
			<a <?php echo $href; ?> href="<?php echo $this->url(array('page' => $this->first)); ?>" title="First" class="pagefirst">&nbsp;</a>
		<?php else: ?>
			<span class="disabled pagefirstoff" title="First">&nbsp;</span>
		<?php endif; if (isset($this->previous)): ?>
			<a <?php echo $href; ?> href="<?php echo $this->url(array('page' => $this->previous)); ?>" title="Previous" class="pageprev">&nbsp;</a>
		<?php else: ?>
			<span class="disabled pageprevoff" title="Previous">&nbsp;</span>
		<?php endif; if (isset($this->next)): ?>
			<a <?php echo $href; ?> href="<?php echo $this->url(array('page' => $this->next)); ?>" title="Next" class="pagenext">&nbsp;</a>
		<?php else: ?>
			<span class="disabled pagenextoff" title="Next">&nbsp;</span>
		<?php endif; if (isset($this->next)): ?>
			<a <?php echo $href; ?> href="<?php echo $this->url(array('page' => $this->last)); ?>" title="Last" class="pagelast">&nbsp;</a>
		<?php else: ?>
			<span class="disabled pagelastoff" title="Last">&nbsp;</span>
		<?php endif; ?>
	<div class="clear <?php if($this->pos == 'top') echo 'tenpx'; ?>"></div>
<?php endif; ?>