<h1><a href="<?php echo $this->url(array("controller" => "attributes", "action" => "list-sets"), "admin", true); ?>"><?php echo $this->translate->_("Attributes"); ?></a> &raquo; <a href="<?php echo $this->url(array("controller" => "attributes", "action" => "list-attributes", "id" => $this->set_id), "admin", true); ?>"><?php echo sprintf($this->translate->_("List Attributes for %s"), $this->set); ?></a> &raquo; <?php echo sprintf($this->translate->_("List Options for %s"), $this->attr); ?></h1>
<div class="rbcontent" id="search_fields">
	<form name="search" action="<?php echo $this->url; ?>" method="get">
	<input type="hidden" name="order" id="order" value="<?php echo $this->order; ?>" />
	<input type="hidden" name="dir" id="dir" value="<?php echo $this->dir; ?>" />
	<table>
	<col width="430" />
		<tr>
			<td>
				<div class="filter_item">
					<label><?php echo $this->translate->_("Value"); ?>:</label>
					<input type="text" name="value" value="<?php echo $this->value; ?>" />
				</div>
			</td>
			<td>
				<div class="filter_item">
					<label></label>
					<input type="button" value="<?php echo $this->translate->_("Search"); ?>" data-type="submit" />
					<input type="button" value="<?php echo $this->translate->_("Reset"); ?>" data-type="reset" />
				</div>
			</td>
		</tr>
	</table>
	</form>
</div>
<?php if(count($this->opts) > 0): ?>
	<?php echo $this->paginationControl($this->opts, 'Elastic', 'controls.phtml', array('translate' => $this->translate)); ?>
	<table class="main">
		<thead>
			<tr>
				<th class="<?php $col = "value"; echo strcasecmp($this->order, $col) == 0 ? strcasecmp($this->dir, "asc") == 0 ? "sortable selectedUp" : "sortable selectedDown" : "sortable"; ?>" nowrap="nowrap" data-col="<?php echo $col; ?>"><?php echo $this->translate->_("Value"); ?></th>
				<th width="1%"></th>
				<th width="1%"></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->opts as $opt): ?>
				<tr>
					<td><a href="<?php echo $this->url(array('controller'=>'attributes', 'action'=>'edit-option', 'id'=> $opt["id"]), 'admin', true); ?>"><?php echo Petolio_Service_Util::Tr($opt['value']); ?></a></td>
					<td nowrap="nowrap" style="text-align: center;"><a href="<?php echo $this->url(array('controller'=>'attributes', 'action'=>'edit-option', 'id'=> $opt["id"]), 'admin', true); ?>"><?php echo $this->translate->_("Edit") ?></a></td>
					<td nowrap="nowrap" style="text-align: center;"><a href="<?php echo $this->url(array('controller'=>'attributes', 'action'=>'delete-option', 'id'=> $opt["id"]), 'admin', true); ?>" class="reqconf" title="<?php echo $this->translate->_("Are you sure you want to delete this option?"); ?>"><?php echo $this->translate->_("Delete"); ?></a></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<?php echo $this->paginationControl($this->opts, 'Elastic', 'controls.phtml', array('translate' => $this->translate)); ?>
<?php else: ?>
	<div class="error"><?php echo $this->translate->_("No records found."); ?></div>
<?php endif; ?>
<form style="background: #fff;">
	<input type="button" onclick="document.location='<?php echo $this->url(array('action' => 'add-option')); ?>';" class="submit" value="<?php echo $this->translate->_("Add Option"); ?>" />
	<div class="clear"></div>
</form>
<script type="text/javascript">
	READY(function() {
		Admin.loadJs('filters/base.js');
		Filters.load('/attributes/list-options/id/<?php echo $this->id; ?>');
	});
</script>