<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translate->_('Print Event'); ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<style type="text/css">
		body {
			font-family: Verdana;
			font-size: 11px;
		}

		.red { color: red !important; }
		.green { color: green !important; }
		.orange { color: orange !important; }
		.grey { color: #999 !important; }

		div.wrap {
			width: 600px;
			margin: 20px auto 0px auto;
			border: 1px solid #ddd;
			padding: 10px;
		}
			h1 {
				padding: 3px;
				margin: 0px 0px 5px 0px;
				float: left;
			}

			h2 {
				padding: 3px;
				margin: 6px 0px 0px 0px;
				float: right;
			}

			.clear {
				clear: both;
				border-bottom: 1px solid #ddd;
				margin: 0px 3px 10px 3px;
			}

			table.jquery-ui-table th {
				text-align: right;
				white-space: nowrap;
				vertical-align: top;
				padding: 2px 10px 2px 2px;
				border-right: 1px solid #ddd;
			}

			table.jquery-ui-table td {
				padding: 2px 2px 2px 10px;
			}
	</style>
</head>
<body onload="window.print();">
	<div class="wrap">
		<h1><?php echo $this->translate->_('Event Details'); ?></h1>
		<h2><?php echo Petolio_Service_Util::formatDate($this->event['timestamp'], Petolio_Service_Util::MEDIUMDATE, true, true); ?></h2>
		<div class="clear"></div>
		<?php echo $this->event['data']; ?>
	</div>
</body>
</html>